### ISSUE TITLE
Error during template compile of 'SharedModule'   Function calls are not supported in decorators but 'FlexLayoutModule' was called.

### ISSUE THREAD

**Issue by GeorgiaData** [xmlking/ngx-starter-kit#4]
The error occurs when running either `npm run build:prod` or `npm run deploy:mock`.
No other changes were made.  Occurs before and after running `npm audit fix`.
To install, I ran `npm install` before `npm run start`
(Would be good to include `npm install`  in the README.md steps.)

**ERROR:** Error during template compile of 'SharedModule'   Function calls are not supported in decorators but 'FlexLayoutModule' was called.

Complete log of run:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/Users/Loren/.npm-packages/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:prod' ]
2 info using npm@6.1.0
3 info using node@v10.0.0
4 verbose run-script [ 'prebuild:prod', 'build:prod', 'postbuild:prod' ]
5 info lifecycle ngx-starter-kit@1.0.0-BETA.1~prebuild:prod: ngx-starter-kit@1.0.0-BETA.1
6 info lifecycle ngx-starter-kit@1.0.0-BETA.1~build:prod: ngx-starter-kit@1.0.0-BETA.1
7 verbose lifecycle ngx-starter-kit@1.0.0-BETA.1~build:prod: unsafe-perm in lifecycle true
8 verbose lifecycle ngx-starter-kit@1.0.0-BETA.1~build:prod: PATH: /Users/Loren/.npm-packages/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Library/Sites/ngx-starter-kit/node_modules/.bin:/anaconda3/bin:/Users/Loren/.node/bin:/Users/Loren/.npm-packages/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin
9 verbose lifecycle ngx-starter-kit@1.0.0-BETA.1~build:prod: CWD: /Library/Sites/ngx-starter-kit
10 silly lifecycle ngx-starter-kit@1.0.0-BETA.1~build:prod: Args: [ '-c', 'ng build -c=production' ]
11 silly lifecycle ngx-starter-kit@1.0.0-BETA.1~build:prod: Returned: code: 1  signal: null
12 info lifecycle ngx-starter-kit@1.0.0-BETA.1~build:prod: Failed to exec build:prod script
13 verbose stack Error: ngx-starter-kit@1.0.0-BETA.1 build:prod: `ng build -c=production`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/Loren/.npm-packages/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/Loren/.npm-packages/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:947:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
14 verbose pkgid ngx-starter-kit@1.0.0-BETA.1
15 verbose cwd /Library/Sites/ngx-starter-kit
16 verbose Darwin 17.6.0
17 verbose argv "/usr/local/bin/node" "/Users/Loren/.npm-packages/bin/npm" "run" "build:prod"
18 verbose node v10.0.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error ngx-starter-kit@1.0.0-BETA.1 build:prod: `ng build -c=production`
22 error Exit status 1
23 error Failed at the ngx-starter-kit@1.0.0-BETA.1 build:prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by xmlking** [comment]
Thanks for the feedback.
we are waiting for for this PR to be merged . https://github.com/angular/flex-layout/pull/779 
meanwhile i am adding the workaround.  please pull latest code.

**Comment by xmlking** [comment]
fixed with latest flex-layout
